#!/usr/bin/env python3
"""Generate the barrier packet artifact header from the artifact JSON.

The script validates the committed JSON schema and emits the generated C
header consumed by the embedded firmware. A freshness check can compare
the generated header with the committed include/packet_artifact.h.
"""

import argparse
import json
import sys
from pathlib import Path

ARTIFACT_FORMAT = "iron-fang-barrier-packets-v1"
DEFAULT_OUTPUT_HEADER = "include/packet_artifact.h"

_FROM_JSON_HELP = (
    "Load existing JSON artifact and emit header without fresh encoding"
)
_HEADER_OUT_HELP = "Output generated C header path"
_CHECK_HEADER_HELP = (
    "Optional path to compare against generated header and fail if stale"
)
_INVALID_JSON = "Artifact JSON at {0} is invalid JSON."
_FORMAT_MISMATCH = (
    "Artifact format must be '{0}', got '{1}'."
)
_FRAME_TOO_LONG = (
    "Example frame must encode to at most frame_size bytes."
)

_HEADER_TEMPLATE = """// MIT License
//
// Copyright (c) 2026 Kevin Thomas
//
// Permission is hereby granted, free of charge, to any person
// obtaining a copy of this software and associated documentation
// files (the "Software"), to deal in the Software without
// restriction, including without limitation the rights to use,
// copy, modify, merge, publish, distribute, sublicense, and/or
// sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following
// conditions:
//
// The above copyright notice and this permission notice shall be
// included in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
// EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
// OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
// NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
// HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
// WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
//
// This file is generated by scripts/gen_packet.py. Do not edit by hand.
// clang-format off

#ifndef PACKET_ARTIFACT_H
#define PACKET_ARTIFACT_H

#include <stdint.h>

#define PACKET_ARTIFACT_FORMAT "{artifact_format}"
#define PACKET_FRAME_VERSION {frame_version}u
#define PACKET_NODE_ADDRESS {node_address}u
#define PACKET_GATEWAY_ADDRESS {gateway_address}
#define PACKET_FRAME_SIZE {frame_size}u
#define PACKET_LINK_WAIT_MS {link_wait_ms}u
#define PACKET_BOOM_RAISE_PULSE_US {raise_pulse_us}u
#define PACKET_BOOM_LOWER_PULSE_US {lower_pulse_us}u
#define PACKET_DHT_TIMEOUT_US {dht_timeout_us}u
#define PACKET_LCD_I2C_ADDRESS {lcd_i2c_address}
#define PACKET_MAX_RCV_LEN {max_rcv_len}u

static const uint8_t PACKET_EXAMPLE_FRAME[{frame_size}] = {{
{frame_body}
}};

#endif // PACKET_ARTIFACT_H
"""


def _parse_json_file(path):
    """Load and parse the artifact JSON file.

    Parameters
    ----------
    path : str
        Artifact JSON file path.

    Returns
    -------
    dict
        Parsed JSON document.
    """
    raw = Path(path).read_text(encoding="utf-8")
    try:
        parsed = json.loads(raw)
    except json.JSONDecodeError as exc:
        raise ValueError(_INVALID_JSON.format(path)) from exc
    return parsed


def _validate_artifact_format(parsed):
    """Reject artifact JSON with an unexpected format marker.

    Parameters
    ----------
    parsed : dict
        Parsed JSON document.

    Returns
    -------
    None
    """
    actual = parsed.get("format")
    if actual != ARTIFACT_FORMAT:
        raise ValueError(_FORMAT_MISMATCH.format(ARTIFACT_FORMAT, actual))


def _int_field(parsed, name):
    """Read one required integer provisioning field.

    Parameters
    ----------
    parsed : dict
        Parsed JSON document.
    name : str
        Field name to read.

    Returns
    -------
    int
        Parsed integer field value.
    """
    try:
        return int(parsed[name])
    except (KeyError, TypeError, ValueError) as exc:
        raise ValueError(
            "Artifact must include integer {0} field.".format(name)
        ) from exc


def _hex_field(parsed, name):
    """Read one required lowercase hexadecimal field.

    Parameters
    ----------
    parsed : dict
        Parsed JSON document.
    name : str
        Field name to read.

    Returns
    -------
    str
        Validated hexadecimal field text.
    """
    value = str(parsed[name])
    int(value, 16)
    return value


def _frame_bytes(example, frame_size):
    """Encode and pad an example frame string.

    Parameters
    ----------
    example : str
        Example telemetry frame body.
    frame_size : int
        Required fixed frame length in bytes.

    Returns
    -------
    bytes
        Padded example frame payload.
    """
    raw = example.encode("utf-8")
    if len(raw) > frame_size:
        raise ValueError(_FRAME_TOO_LONG)
    return raw + bytes(frame_size - len(raw))


def _artifact_from_parsed(parsed):
    """Reconstruct the canonical artifact dict from parsed JSON.

    Parameters
    ----------
    parsed : dict
        Parsed JSON document.

    Returns
    -------
    dict
        Canonical packet artifact dictionary.
    """
    _validate_artifact_format(parsed)
    frame_size = _int_field(parsed, "frame_size")
    example_frame = _frame_bytes(str(parsed["example_frame"]), frame_size)
    return {
        "format": ARTIFACT_FORMAT,
        "frame_version": _int_field(parsed, "frame_version"),
        "node_address": _int_field(parsed, "node_address"),
        "gateway_address": _hex_field(parsed, "gateway_address_hex"),
        "frame_size": frame_size,
        "link_wait_ms": _int_field(parsed, "link_wait_ms"),
        "raise_pulse_us": _int_field(parsed, "raise_pulse_us"),
        "lower_pulse_us": _int_field(parsed, "lower_pulse_us"),
        "dht_timeout_us": _int_field(parsed, "dht_timeout_us"),
        "lcd_i2c_address": _hex_field(parsed, "lcd_i2c_address_hex"),
        "max_rcv_len": _int_field(parsed, "max_rcv_len"),
        "example_frame": example_frame,
    }


def _load_artifact_json(path):
    """Load and validate an artifact JSON for header generation.

    Parameters
    ----------
    path : str
        Artifact JSON file path.

    Returns
    -------
    dict
        Canonical artifact dictionary.
    """
    parsed = _parse_json_file(path)
    return _artifact_from_parsed(parsed)


def _format_c_array(data, width=8):
    """Format bytes as an indented C array literal body.

    Parameters
    ----------
    data : bytes
        Bytes to serialize as a C array.
    width : int
        Byte values emitted per source line.

    Returns
    -------
    str
        Indented, comma-joined C array body.
    """
    items = [f"0x{value:02X}u" for value in data]
    rows = [", ".join(items[offset:offset + width])
            for offset in range(0, len(items), width)]
    return ",\n".join("    " + row for row in rows)


def _render_header(artifact):
    """Render the generated firmware header text from the artifact.

    Parameters
    ----------
    artifact : dict
        Canonical packet artifact dictionary.

    Returns
    -------
    str
        Complete generated C header text.
    """
    return _HEADER_TEMPLATE.format(
        artifact_format=artifact["format"],
        frame_version=artifact["frame_version"],
        node_address=artifact["node_address"],
        gateway_address="0x{0:04X}u".format(
            int(artifact["gateway_address"], 16)),
        frame_size=artifact["frame_size"],
        link_wait_ms=artifact["link_wait_ms"],
        raise_pulse_us=artifact["raise_pulse_us"],
        lower_pulse_us=artifact["lower_pulse_us"],
        dht_timeout_us=artifact["dht_timeout_us"],
        lcd_i2c_address="0x{0:X}u".format(
            int(artifact["lcd_i2c_address"], 16)),
        max_rcv_len=artifact["max_rcv_len"],
        frame_body=_format_c_array(artifact["example_frame"]),
    )


def _write_header(path, artifact):
    """Write the generated firmware header from the packet artifact.

    Parameters
    ----------
    path : str
        Destination header file path.
    artifact : dict
        Canonical packet artifact dictionary.

    Returns
    -------
    Path
        Resolved destination header path.
    """
    output_path = Path(path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(_render_header(artifact), encoding="utf-8")
    return output_path.resolve()


def _check_header_match(generated_path, expected_path):
    """Fail when the generated header does not match an expected file.

    Parameters
    ----------
    generated_path : str
        Generated header file path.
    expected_path : str
        Expected committed header file path.

    Returns
    -------
    None
    """
    generated = Path(generated_path).read_text(encoding="utf-8")
    expected = Path(expected_path).read_text(encoding="utf-8")
    if generated != expected:
        raise RuntimeError(
            "Generated header does not match committed "
            "include/packet_artifact.h. Regenerate and commit "
            "updated artifacts with scripts/gen_packet.py."
        )


def _print_header_check(header_path, expected_path):
    """Print the verified header match result.

    Parameters
    ----------
    header_path : str
        Generated header file path.
    expected_path : str
        Expected committed header file path.

    Returns
    -------
    None
    """
    _check_header_match(header_path, expected_path)
    print("Verified header matches: {0}".format(Path(expected_path).resolve()))


def _parse_args():
    """Parse command-line arguments.

    Parameters
    ----------
    None

    Returns
    -------
    argparse.Namespace
        Parsed command-line arguments.
    """
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--from-json", help=_FROM_JSON_HELP)
    parser.add_argument("--header-out", default=DEFAULT_OUTPUT_HEADER,
                        help=_HEADER_OUT_HELP)
    parser.add_argument("--check-header-path", help=_CHECK_HEADER_HELP)
    return parser.parse_args()


def _flush_from_json(args):
    """Write the header from an existing artifact JSON.

    Parameters
    ----------
    args : argparse.Namespace
        Parsed command-line arguments.

    Returns
    -------
    Path
        Resolved generated header path.
    """
    artifact = _load_artifact_json(args.from_json)
    header_path = _write_header(args.header_out, artifact)
    print("Wrote generated firmware header: {0}".format(header_path))
    return header_path


def main():
    """Generate the packet artifact C header from committed JSON.

    Parameters
    ----------
    None

    Returns
    -------
    None
    """
    args = _parse_args()
    if not args.from_json:
        raise SystemExit("Usage: gen_packet.py --from-json <artifact.json> "
                         "[--header-out <path>] [--check-header-path <path>]")
    header_path = _flush_from_json(args)
    if args.check_header_path:
        _print_header_check(header_path, args.check_header_path)


if __name__ == "__main__":
    main()