// MIT License
//
// Copyright (c) 2026 Kevin Thomas
//
// Permission is hereby granted, free of charge, to any person
// obtaining a copy of this software and associated documentation
// files (the "Software"), to deal in the Software without
// restriction, including without limitation the rights to use,
// copy, modify, merge, publish, distribute, sublicense, and/or
// sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following
// conditions:
//
// The above copyright notice and this permission notice shall be
// included in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
// EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
// OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
// NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
// HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
// WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
//
// This file is generated by scripts/gen_packet.py. Do not edit by hand.
// clang-format off

#ifndef PACKET_ARTIFACT_H
#define PACKET_ARTIFACT_H

#include <stdint.h>

#define PACKET_ARTIFACT_FORMAT "iron-fang-barrier-packets-v1"
#define PACKET_FRAME_VERSION 1u
#define PACKET_NODE_ADDRESS 7u
#define PACKET_GATEWAY_ADDRESS 0x0001u
#define PACKET_FRAME_SIZE 48u
#define PACKET_LINK_WAIT_MS 5000u
#define PACKET_BOOM_RAISE_PULSE_US 1500u
#define PACKET_BOOM_LOWER_PULSE_US 500u
#define PACKET_DHT_TIMEOUT_US 240u
#define PACKET_LCD_I2C_ADDRESS 0x27u
#define PACKET_MAX_RCV_LEN 256u

static const uint8_t PACKET_EXAMPLE_FRAME[48] = {
    0x7Bu, 0x22u, 0x65u, 0x76u, 0x74u, 0x22u, 0x3Au, 0x22u,
    0x72u, 0x61u, 0x69u, 0x73u, 0x65u, 0x22u, 0x2Cu, 0x22u,
    0x62u, 0x6Fu, 0x6Fu, 0x6Du, 0x22u, 0x3Au, 0x31u, 0x7Du,
    0x00u, 0x00u, 0x00u, 0x00u, 0x00u, 0x00u, 0x00u, 0x00u,
    0x00u, 0x00u, 0x00u, 0x00u, 0x00u, 0x00u, 0x00u, 0x00u,
    0x00u, 0x00u, 0x00u, 0x00u, 0x00u, 0x00u, 0x00u, 0x00u
};

#endif // PACKET_ARTIFACT_H
